name: Script Validation
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  runscript:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Test Azure
        run:  ${GITHUB_WORKSPACE}/az/az_check.sh -h
      - name: Test AWS
        run:  ${GITHUB_WORKSPACE}/aws/aws_check.sh -h
      - name: Test GCP 
        run:  ${GITHUB_WORKSPACE}/gcp/gcp_check.sh -h
      - name: Test OCI
        run:  ${GITHUB_WORKSPACE}/oci/oci_check.sh -h
      - name: Test OCI
        run:  ${GITHUB_WORKSPACE}/openshift/openshift_check.sh -h