name: Script Validation
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  runscript:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Azure
        run:  ${GITHUB_WORKSPACE}/az/az_check.sh -h
      - name: Test AWS
        run:  ${GITHUB_WORKSPACE}/aws/aws_check.sh -h
      - name: Test GCP 
        run:  ${GITHUB_WORKSPACE}/gcp/gcp_check.sh -h
